export const REMOVE_ROUTE_DISTRICT = "REMOVE_ROUTE_DISTRICT";
export const ADD_ROUTE_DISTRICT = "ADD_ROUTE_DISTRICT";
export const ADD_ROUTE_DISTRICTLIST = "ADD_ROUTE_DISTRICTLIST";
export const REMOVE_ROUTE_DISTRICTLIST = "REMOVE_ROUTE_DISTRICTLIST";
